import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { getStudyTips } from '../api/recommend';

export default function AIHelpModal({ isOpen, onClose, explanation, mode = 'student' }) {
  const [tips, setTips] = useState(null);

  const tipsMutation = useMutation({
    mutationFn: () => getStudyTips({
      risk_score:   explanation?.risk_score ?? 0.5,
      risk_label:   explanation?.risk_label ?? 'Medium',
      top_features: explanation?.top_features ?? [],
      shap_values:  explanation?.shap_values ?? {},
      anchor_rule:  explanation?.anchor_rule ?? {},
    }),
    onSuccess: setTips,
  });

  const handleOpen = () => {
    if (!tips && !tipsMutation.isPending) {
      tipsMutation.mutate();
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={onClose} />
      <div className="relative bg-surface rounded-2xl shadow-2xl border border-outline-variant/10 w-full max-w-lg mx-auto overflow-hidden">
        <div className="bg-gradient-to-r from-primary to-primary-container p-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-white/20 flex items-center justify-center">
                <span className="material-symbols-outlined text-white text-xl" style={{ fontVariationSettings: "'FILL' 1" }}>smart_toy</span>
              </div>
              <div>
                <h2 className="font-headline font-bold text-white text-lg">AI Study Coach</h2>
                <p className="text-white/70 text-xs font-label">Powered by your XAI explanation</p>
              </div>
            </div>
            <button onClick={onClose} className="text-white/60 hover:text-white transition-colors">
              <span className="material-symbols-outlined">close</span>
            </button>
          </div>
        </div>

        <div className="p-6">
          {!tips && !tipsMutation.isPending && (
            <div className="text-center py-6">
              <p className="text-on-surface/60 text-sm font-label mb-4">
                Get personalised study tips based on your dropout risk analysis.
              </p>
              <button
                onClick={handleOpen}
                className="px-6 py-3 bg-primary text-on-primary rounded-xl font-bold text-sm hover:bg-primary/90 transition-colors flex items-center gap-2 mx-auto"
              >
                <span className="material-symbols-outlined text-sm">bolt</span>
                Generate My Tips
              </button>
            </div>
          )}

          {tipsMutation.isPending && (
            <div className="flex flex-col items-center py-8 gap-3">
              <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin" />
              <p className="text-on-surface/50 text-sm font-label">Analysing your learning data...</p>
            </div>
          )}

          {tips && (
            <div className="space-y-4">
              <div className="bg-primary/5 rounded-xl p-4 border border-primary/10">
                <p className="text-sm text-on-surface/80 leading-relaxed italic">"{tips.summary}"</p>
              </div>
              <div className="space-y-3">
                {(tips.tips ?? []).map((tip, i) => (
                  <div key={i} className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-primary flex items-center justify-center shrink-0 mt-0.5">
                      <span className="text-on-primary text-xs font-bold">{i + 1}</span>
                    </div>
                    <p className="text-sm text-on-surface/80 leading-relaxed">{tip}</p>
                  </div>
                ))}
              </div>
              {tips.source === 'llm' && (
                <p className="text-[10px] text-slate-400 font-label text-right">Generated by Groq LLM · grounded in your XAI data</p>
              )}
              <button
                onClick={() => { setTips(null); tipsMutation.reset(); }}
                className="w-full py-2 text-xs font-label text-slate-400 hover:text-primary transition-colors"
              >
                Regenerate tips
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
