"""initial_schema

Revision ID: 0d652f39389c
Revises: 
Create Date: 2026-04-11 17:16:05.518631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d652f39389c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explanation_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=32), nullable=True),
    sa.Column('top3_features', sa.Text(), nullable=False),
    sa.Column('shap_values', sa.Text(), nullable=False),
    sa.Column('anchor_rule', sa.Text(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explanation_records_learner_id'), 'explanation_records', ['learner_id'], unique=False)
    op.create_table('feedback_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('explanation_id', sa.String(length=64), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('followed_recommendation', sa.Boolean(), nullable=True),
    sa.Column('top_action_feature', sa.String(length=64), nullable=True),
    sa.Column('correction_feature', sa.String(length=64), nullable=True),
    sa.Column('correction_comment', sa.Text(), nullable=True),
    sa.Column('trust_score_at_time', sa.Float(), nullable=True),
    sa.Column('risk_score_at_time', sa.Float(), nullable=True),
    sa.Column('audience', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_records_explanation_id'), 'feedback_records', ['explanation_id'], unique=False)
    op.create_index(op.f('ix_feedback_records_learner_id'), 'feedback_records', ['learner_id'], unique=False)
    op.create_table('interaction_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_target', sa.String(length=128), nullable=True),
    sa.Column('event_value', sa.Float(), nullable=True),
    sa.Column('page', sa.String(length=64), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('client_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_events_event_type'), 'interaction_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_interaction_events_learner_id'), 'interaction_events', ['learner_id'], unique=False)
    op.create_index(op.f('ix_interaction_events_session_id'), 'interaction_events', ['session_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('instructor_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('learner_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=True),
    sa.Column('module_presentation', sa.String(length=32), nullable=True),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('prior_completions', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_learner_profiles_learner_id'), 'learner_profiles', ['learner_id'], unique=True)
    op.create_table('course_enrollments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('learner_profile_id', sa.String(), nullable=False),
    sa.Column('instructor_profile_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instructor_profile_id'], ['instructor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_profile_id', 'instructor_profile_id', 'course_id', name='uq_enrollment')
    )
    op.create_index(op.f('ix_course_enrollments_course_id'), 'course_enrollments', ['course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_enrollments_course_id'), table_name='course_enrollments')
    op.drop_table('course_enrollments')
    op.drop_index(op.f('ix_learner_profiles_learner_id'), table_name='learner_profiles')
    op.drop_table('learner_profiles')
    op.drop_table('instructor_profiles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_interaction_events_session_id'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_learner_id'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_event_type'), table_name='interaction_events')
    op.drop_table('interaction_events')
    op.drop_index(op.f('ix_feedback_records_learner_id'), table_name='feedback_records')
    op.drop_index(op.f('ix_feedback_records_explanation_id'), table_name='feedback_records')
    op.drop_table('feedback_records')
    op.drop_index(op.f('ix_explanation_records_learner_id'), table_name='explanation_records')
    op.drop_table('explanation_records')
    # ### end Alembic commands ###
